# Generated by Django 5.0.2 on 2024-02-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForwardManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ForwardManyToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ForwardOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "example_state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        max_length=255,
                    ),
                ),
                ("duration", models.DurationField()),
                ("symmetrical_field", models.ManyToManyField(to="example.example")),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="example_rels", to="example.forwardmanytomany"
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_rels",
                        to="example.forwardmanytoone",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_rel",
                        to="example.forwardonetoone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReverseManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels", to="example.example"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReverseOneToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="example.example",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReverseOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="example.example",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="example",
            constraint=models.UniqueConstraint(
                fields=("name", "number"),
                name="unique_name",
                violation_error_message="Example unique violation message.",
            ),
        ),
        migrations.AddConstraint(
            model_name="example",
            constraint=models.CheckConstraint(
                check=models.Q(("name__icontains", "foo")),
                name="check_example",
                violation_error_message="Example constraint violation message.",
            ),
        ),
    ]
